name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
    paths:
      # Build when source code changes
      - "src/**"
      - "public/**"
      # Build when dependencies change
      - "package.json"
      - "yarn.lock"
      # Build when config files change
      - "*.config.js"
      - "*.config.ts"
      - "tsconfig.json"
      - "vite.config.ts"
      # Build when app files change
      - "index.html"
      # Build when formatting configs change (affects output)
      - ".prettierrc"
      - ".editorconfig"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
  # Allow manual workflow runs for testing or emergency deployments
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    # Build when manually triggered, or when pushing to main, or when PR is opened/updated
    # For PRs, only build if relevant files changed (paths filter doesn't work on PR events properly)
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build site
        run: yarn build
        env:
          # Use dev Supabase for PR previews, prod for main branch
          VITE_SUPABASE_URL: ${{ github.event_name == 'pull_request' && secrets.VITE_SUPABASE_URL_DEV || secrets.VITE_SUPABASE_URL_PROD }}
          VITE_SUPABASE_ANON_KEY: ${{ github.event_name == 'pull_request' && secrets.VITE_SUPABASE_ANON_KEY_DEV || secrets.VITE_SUPABASE_ANON_KEY_PROD }}
          VITE_APP_NAME: Chore Domino
          VITE_APP_VERSION: ${{ github.sha }}
          VITE_ENV: ${{ github.event_name == 'pull_request' && 'preview' || 'production' }}

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          output_location: "dist"
          skip_app_build: true

  close_pull_request_environment:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Close pull request environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: close
          app_location: "/"
